//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Horizoft.Relay.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Host
    {
        public int Id { get; set; }
        public string URL { get; set; }
        public string Protocal { get; set; }
        public Nullable<int> Port { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}
